images:
  - "png"
  - "jpg"
  - "jpeg"
  - "gif"
  - "svg"
  - "webp"
  - "heif"
  - "avif"
  - "tiff"
  - "bmp"
video:
  - "mp4"
  - "avi"
  - "webm"
  - "flv"
  - "mkv"
  - "ogg"
  - "gifv"
  - "mov"
  - "qt"
  - "wmv"
  - "m4p"
  - "m4v"
audio:
  - "mp3"
  - "wav"
documents:
  - "doc"
  - "docx"
  - "ppt"
  - "pptx"
  - "xls"
  - "xlsx"
  - "pdf"
  - "txt"
archives:
  - "zip"
  - "tar"
  - "rar"
  - "iso"
  - "gz"
  - "7z"
  - "apk"
  - "jar"
torrent:
  - "tor"
setup:
  - "exe"
  - "msi"
